web1pato/urls.py
from django.urls import path
from django.contrib import admin
from web import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'estudiantes'


urlpatterns = [
     path('admin/', admin.site.urls),
    path('hola/', views.welcome_view, name='welcome'),  
    path('registro/', views.register_view, name='register'),
    path('', views.login_view, name='login'),
    path('dashboard/', views.home_view, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.password_reset_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),

    path('registro_estuiante/', views.solicitud_matricula, name='registro_estudiante'),


    path ('materia/', views.materia, name='materias'),

    path('formulario/', views.formulario_datos, name='formulario_datos'),
    path('display/', views.display_data, name='display_data'),
    path('download_data/', views.download_data, name='download_data'),
    path('actualizar/', views.actualizar_datos_estudiante, name='actualizar_datos_estudiante'),

       path('subir_pdf/', views.subir_pdf, name='subir_pdf'),
    path('eliminar_pdf/<int:pdf_id>/', views.eliminar_pdf, name='eliminar_pdf'),
    path('descargar/<int:pdf_id>/<str:version>/', views.descargar_version_pdf, name='descargar_version_pdf'),
    path('editar_pdf/<int:pdf_id>/', views.editar_pdf, name='editar_pdf'),
    path('descargar_pdf/<int:pdf_id>/', views.descargar_version_pdf, name='descargar_version_pdf'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Agregar campos adicionales para el perfil del usuario si es necesario
    # Ejemplo: nombre, apellido, fecha de nacimiento, etc.

    def __str__(self):
        return self.user.username
    

    

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100)
    carrera = models.CharField(max_length=100)
    semestre = models.IntegerField()

    def __str__(self):
        return self.nombre


    
GENDER_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Femenino'),
    ('O', 'Otro'),
]

class DatosEstudiante(models.Model):
    foto = models.ImageField(upload_to='profile_photos/')
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField()
    genero = models.CharField(max_length=1, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    direccion = models.TextField()
    ciudad = models.CharField(max_length=100)
    pais = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre + ' ' + self.apellido
    
class DocumentoPDF(models.Model):
    nombre = models.CharField(max_length=100)
    archivo_pdf = models.FileField(upload_to='pdfs/')
    materia = models.CharField(max_length=100)
    version = models.CharField(max_length=20, null=True, blank=True)
    fecha_subida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

web/templates/pag/cargar_notas.html
<!DOCTYPE html>
<html>
<head>
    <title>Cargar Notas</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f2f5;
            margin: 20px;
        }

        h1 {
            color: #7289da;
            border-bottom: 1px solid #7289da;
            padding-bottom: 5px;
        }

        form {
            background-color: #fff;
            border: 1px solid #e1e3e6;
            padding: 20px;
            margin-top: 20px;
        }

        label {
            font-weight: bold;
        }

        select, input {
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            width: 100%;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: #7289da;
            color: #fff;
            cursor: pointer;
            transition: background-color 0.2s;
        }

        input[type="submit"]:hover {
            background-color: #677bc4;
        }

        h2 {
            color: #7289da;
            margin-top: 30px;
            border-bottom: 1px solid #7289da;
            padding-bottom: 5px;
        }

        ul {
            list-style: none;
            padding-left: 0;
        }

        li {
            padding: 5px 0;
            border-bottom: 1px solid #ccc;
        }
    </style>
</head>
<body>
    <h1>Cargar Notas de Estudiantes</h1>
    <form method="post">
        {% csrf_token %}
        <label for="nombre_estudiante">Nombre y Apellido del Estudiante:</label>
        <select name="nombre_estudiante" id="nombre_estudiante">
            {% for estudiante in estudiantes %}
                <option value="{{ estudiante.nombre }}">{{ estudiante.nombre }}</option>
            {% endfor %}
        </select>
        <label for="materia">Materia:</label>
        <select name="materia" id="materia">
            {% for materia_choice in form.fields.materia.choices %}
                <option value="{{ materia_choice.0 }}">{{ materia_choice.1 }}</option>
            {% endfor %}
        </select>
        <label for="nota">Nota:</label>
        <input type="number" step="0.01" name="nota" id="nota" required>
        <br>
        <input type="submit" value="Guardar Nota">
    </form>
    <h2>Notas Registradas:</h2>
    <ul>
        {% for nota in notas %}
            <li>{{ nota.estudiante }} - {{ nota.materia }}: {{ nota.nota }}</li>
        {% endfor %}
    </ul>
</body>
</html>

web/templates/pag/display_data.html
<!-- display_data.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Datos del Estudiante</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 20px;
        }
        h1 {
            color: #007bff;
            text-align: center;
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            border-bottom: 1px solid #ccc;
        }
        th {
            background-color: #f2f2f2;
        }
        .custom-button {
            display: inline-block;
            background-color: #2ecc71;
            color: #fff;
            padding: 5px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
            margin-right: 10px;
        }
        .image-container {
            width: 200px;
            height: 200px;
            border: 1px solid #ccc;
            border-radius: 5px;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }
        .image-container img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <h1>Datos del Estudiante</h1>
    <div class="image-container">
        <img src="{{ datos_estudiante.foto.url }}" alt="Foto de perfil">
    </div>
    <table>
        <tr>
            <th>Nombre:</th>
            <td>{{ datos_estudiante.nombre }}</td>
        </tr>
        <tr>
            <th>Apellido:</th>
            <td>{{ datos_estudiante.apellido }}</td>
        </tr>
        <tr>
            <th>Correo electrónico:</th>
            <td>{{ datos_estudiante.email }}</td>
        </tr>
        <tr>
            <th>Teléfono:</th>
            <td>{{ datos_estudiante.telefono }}</td>
        </tr>
        <tr>
            <th>Fecha de Nacimiento:</th>
            <td>{{ datos_estudiante.fecha_nacimiento }}</td>
        </tr>
        <tr>
            <th>Género:</th>
            <td>{{ datos_estudiante.get_genero_display }}</td>
        </tr>
        <tr>
            <th>Dirección:</th>
            <td>{{ datos_estudiante.direccion }}</td>
        </tr>
        <tr>
            <th>Ciudad:</th>
            <td>{{ datos_estudiante.ciudad }}</td>
        </tr>
        <tr>
            <th>País:</th>
            <td>{{ datos_estudiante.pais }}</td>
        </tr>
    </table>

    <a href="{% url 'actualizar_datos_estudiante' %}" class="custom-button">Editar</a>
    <a href="{% url 'download_data' %}" class="custom-button">Descargar PDF</a>
</body>
</html>

web/templates/pag/editar_pdf.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar PDF - Estilo Futurista</title>
    <style>
        body {
            font-family: 'Helvetica Neue', sans-serif;
            background-color: #121212;
            color: #FFFFFF;
            margin: 0;
            padding: 0;
        }

        h2 {
            text-align: center;
            margin-top: 20px;
            color: #FFFFFF;
            background-color: #3EA6FF; /* Celeste */
            padding: 10px;
            border-radius: 5px;
            letter-spacing: 2px;
            text-transform: uppercase;
        }

        form {
            max-width: 400px;
            margin: 20px auto;
            background-color: #1E1E1E;
            padding: 20px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
            border-radius: 10px;
        }

        form label {
            display: block;
            margin-top: 10px;
            color: #FFFFFF;
            font-weight: bold;
        }

        form input[type="text"],
        form input[type="file"],
        form select {
            width: 100%;
            padding: 12px;
            margin-bottom: 10px;
            border: 2px solid #3EA6FF; /* Celeste */
            border-radius: 8px;
            background-color: #121212;
            color: #FFFFFF;
            outline: none;
            transition: border-color 0.3s, background-color 0.3s;
        }

        form input[type="text"]:focus,
        form input[type="file"]:focus,
        form select:focus {
            border-color: #3EA6FF; /* Celeste */
            background-color: #1E1E1E;
            box-shadow: 0 0 10px #3EA6FF; /* Celeste */
        }

        form button[type="submit"] {
            background-color: #3EA6FF; /* Celeste */
            color: #FFFFFF;
            padding: 12px 24px;
            border: none;
            cursor: pointer;
            font-size: 16px;
            border-radius: 8px;
            width: 100%;
            outline: none;
            text-transform: uppercase;
            letter-spacing: 2px;
            transition: background-color 0.3s;
        }

        form button[type="submit"]:hover {
            background-color: #55b8ff; /* Tonos más oscuros de celeste */
        }

        .file-upload {
            position: relative;
            overflow: hidden;
            background-color: #3EA6FF; /* Celeste */
            color: #FFFFFF;
            padding: 15px;
            text-align: center;
            cursor: pointer;
            border-radius: 8px;
            transition: background-color 0.3s;
        }

        .file-upload p {
            margin: 0;
            font-size: 16px;
        }

        .file-upload input[type="file"] {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            opacity: 0;
            cursor: pointer;
        }

        .file-upload span {
            display: block;
            font-size: 14px;
            font-weight: bold;
            margin-top: 10px;
            color: #FFFFFF;
        }

        .file-upload:hover {
            background-color: #55b8ff; /* Tonos más oscuros de celeste */
        }

        h2 + ul {
            max-width: 400px;
            margin: 20px auto;
            background-color: #1E1E1E;
            padding: 20px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
            border-radius: 10px;
        }

        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        ul li {
            margin-bottom: 10px;
        }

        ul li a {
            color: #3EA6FF; /* Celeste */
            text-decoration: none;
        }

        ul li a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h2>Editar Version</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_nombre">Nombre del PDF:</label>
        {{ form.nombre }}

        <div class="file-upload">
            <p>Arrastra y suelta el archivo aquí o</p>
            <label for="file-upload" class="file-upload-label">Haz clic para seleccionar un archivo</label>
            <input type="file" id="file-upload" name="archivo_pdf" onchange="displayFileName()"/>
            <span id="file-name">Ningún archivo seleccionado</span>
        </div>

        <label for="id_materia">Materia:</label>
        {{ form.materia }}

        <button type="submit">Guardar Cambios</button>
    </form>

    <script>
        function displayFileName() {
            const fileInput = document.getElementById('file-upload');
            const fileNameSpan = document.getElementById('file-name');
            fileNameSpan.textContent = fileInput.files[0] ? fileInput.files[0].name : 'Ningún archivo seleccionado';
        }
    </script>
</body>
</html>

web/templates/pag/formulario.html
<!DOCTYPE html>
<html>
<head>
    <title>Formulario de Datos Personales</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 20px;
        }
        h1 {
            color: #007bff;
            text-align: center;
            margin-bottom: 30px;
        }
        form {
            max-width: 800px; /* Ajusta el ancho según tus necesidades */
            margin: 0 auto;
            background-color: #fff;
            border: 1px solid #ccc;
            padding: 60px;
            border-radius: 5px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        .form-group {
            width: calc(50% - 10px); /* Ajusta el ancho según tus necesidades */
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .form-group input[type="text"], .form-group input[type="email"], .form-group select, .form-group input[type="date"], .form-group input[type="file"], .form-group textarea {
            width: 95%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        .form-group textarea {
            resize: vertical;
        }
        .image-container {
            width: 200px;
            height: 200px;
            left: auto;
            
            border: 1px solid #ccc;
            border-radius: 5px;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }
        .image-container img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }
        .upload-btn {
            margin-top: 5px;
            display: block;
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .upload-btn:hover {
            background-color: #0056b3;
        }
.custom-button {
  display: inline-block;
  background-color: #2ecc71;
  color: #fff;
  padding: 5px 100px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
    </style>
</head>
<body>
    <h1>Formulario de Datos Personales</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="foto">Foto de Perfil:</label>
            <div class="image-container">
                <img src="{% if datos_estudiante.foto %}{{ datos_estudiante.foto.url }}{% else %}{{ image_placeholder_url }}{% endif %}" alt="Foto de perfil" id="image-preview">
            </div>
            <label for="foto" class="upload-btn">Subir foto</label>
            <input type="file" id="foto" name="foto" accept="image/*" style="display:none;" onchange="previewImage(event)">
        </div>
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" value="{{ datos_estudiante.nombre }}" required>
        </div>

        <div class="form-group">
            <label for="apellido">Apellido:</label>
            <input type="text" id="apellido" name="apellido" value="{{ datos_estudiante.apellido }}" required>
        </div>

        <div class="form-group">
            <label for="email">Correo electrónico:</label>
            <input type="email" id="email" name="email" value="{{ datos_estudiante.email }}" required>
        </div>

        <div class="form-group">
            <label for="telefono">Teléfono:</label>
            <input type="text" id="telefono" name="telefono" value="{{ datos_estudiante.telefono }}" required>
        </div>

        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
            <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" value="{{ datos_estudiante.fecha_nacimiento|default:'' }}" required>
        </div>

        <div class="form-group">
            <label for="genero">Género:</label>
            <select id="genero" name="genero" required>
                <option value="" disabled{% if not datos_estudiante.genero %} selected{% endif %}>-- Selecciona --</option>
                <option value="M"{% if datos_estudiante.genero == 'M' %} selected{% endif %}>Masculino</option>
                <option value="F"{% if datos_estudiante.genero == 'F' %} selected{% endif %}>Femenino</option>
                <option value="O"{% if datos_estudiante.genero == 'O' %} selected{% endif %}>Otro</option>
            </select>
        </div>

        <div class="form-group">
            <label for="direccion">Dirección:</label>
            <textarea id="direccion" name="direccion"  required>{{ datos_estudiante.direccion }}</textarea>
        </div>

        <div class="form-group">
            <label for="ciudad">Ciudad:</label>
            <input type="text" id="ciudad" name="ciudad" value="{{ datos_estudiante.ciudad }}">
        </div>

        <div class="form-group">
            <label for="pais">País:</label>
            <input type="text" id="pais" name="pais" value="{{ datos_estudiante.pais }}">
        </div>


        <button type="submit" class="custom-button">Guardar</button>
    </form>
 
 

    <script>
        function previewImage(event) {
            var imagePreview = document.getElementById('image-preview');
            imagePreview.src = URL.createObjectURL(event.target.files[0]);
        }

        function resetImage() {
            var imagePreview = document.getElementById('image-preview');
            imagePreview.src = '';
            var inputFile = document.getElementById('foto');
            inputFile.value = '';
        }
    </script>
</body>
</html>